import Foundation

//region PAFcode define
let PREAMBLE1: UInt8 = 0xAA;
let PREAMBLE2: UInt8 = 0xA5;

let DID_DEVICE_PARAM1: UInt8 = 0x01; //level 1
let DID_WRITE_UNIT_DATA1: UInt8 = 0x0a; //level 1

let DID_MOTOR_RPM: UInt8 = 0x01;
let DID_MOTOR_CURRENT: UInt8 = 0x02;
let DID_MOTOR_TEMP: UInt8 = 0x03;
let DID_BATT_VOLTAGE: UInt8 = 0x04;
let DID_BATT_CURRENT: UInt8 = 0x05;
let DID_BATT_TEMP: UInt8 = 0x06;
let DID_PRESSURE: UInt8 = 0x07;
let DID_BREATHING_RATE: UInt8 = 0x08;
let DID_BREATHING_EFFORT: UInt8 = 0x09;
let DID_BATT_STATE: UInt8 = 0x0a;
let DID_VIN_VOLTAGE: UInt8 = 0x0b;
let DID_FAULT_CODE: UInt8 = 0x0c;
let DID_MOTOR_STATE: UInt8 = 0x0d;
let DID_FLOWX10: UInt8 = 0x0e;

let DID_CYCLE_MIN_PRESSURE: UInt8 = 0x10;
let DID_CYCLE_MAX_PRESSURE: UInt8 = 0x11;
let DID_CYCLE_MAX_RPM: UInt8 = 0x12;
let DID_CYCLE_MIN_RPM: UInt8 = 0x13;
let DID_CYCLE_BATT_VOLTAGE: UInt8 = 0x14;
let DID_CYCLE_NEG_PRESSURE_SCORE: UInt8 = 0x15;
let DID_CYCLE_TARGET_PRESSURE: UInt8 = 0x16;
let DID_CYCLE_AVERAGED_CURRENT: UInt8 = 0x17;
let DID_CYCLE_NUMBER: UInt8 = 0x18;
let DID_CYCLE_LENGTH: UInt8 = 0x19;
let DID_CYCLE_VOLUME: UInt8 = 0x1a;
let DID_FILTER_STATE: UInt8 = 0x1b;
let DID_SESSION_NUMBER: UInt8 = 0x1c;
let DID_RAW_PRESSURE_ADC: UInt8 = 0x1d;

let DID_DEV_CURRENT_MODE: UInt8 = 0x20;
let DID_TOTAL_RUN_MIN_SINCE_FULL_CHARGE: UInt8 = 0x21;
let DID_TOTAL_RUN_MIN_SINCE_LAST_CHARGE: UInt8 = 0x22;
let DID_TOTAL_RUN_MIN_SINCE_FOREVER: UInt8 = 0x23;
let DID_MODEL_TYPE: UInt8 = 0x24;
let DID_SW_MAJOR_VERSION_NO: UInt8 = 0x25;
let DID_SW_MINOR_VERSION_NO: UInt8 = 0x26;
let DID_SYNC_ID: UInt8 = 0x29;
let DID_TOTAL_RUN_MIN_SINCE_FOREVER_2: UInt8 = 0x2a;

let DID_RUNNING_WHILE_CHARGING_ALLOWED: UInt8 = 0x2b;
let DID_STAT_MOTOR_START_COUNT: UInt8 = 0x2c;
let DID_STAT_FULL_CHARGE_COUNT: UInt8 = 0x2d;
let DID_STAT_PLUG_IN_COUNT: UInt8 = 0x2e;
let DID_STAT_BATT_ERROR_COUNT: UInt8 = 0x2f;




let DID_FILTER_BLOCK_C2_1: UInt8 = 0x30;
let DID_FILTER_BLOCK_C2_2: UInt8 = 0x31;
let DID_FILTER_BLOCK_C1_1: UInt8 = 0x32;
let DID_FILTER_BLOCK_C1_2: UInt8 = 0x33;
let DID_FILTER_BLOCK_C0_1: UInt8 = 0x34;
let DID_FILTER_BLOCK_C0_2: UInt8 = 0x35;
let DID_FILTER_CLEAN_C2_1: UInt8 = 0x36;
let DID_FILTER_CLEAN_C2_2: UInt8 = 0x37;
let DID_FILTER_CLEAN_C1_1: UInt8 = 0x38;
let DID_FILTER_CLEAN_C1_2: UInt8 = 0x39;
let DID_FILTER_CLEAN_C0_1: UInt8 = 0x3a;
let DID_FILTER_CLEAN_C0_2: UInt8 = 0x3b;
let DID_FILTER_CLEAN_POWER_CAL: UInt8 = 0x3c;
let DID_FILTER_CLEAN_POWER_CAL_DONE: UInt8 = 0x3d;
let DID_FILTER_TYPE: UInt8 = 0x3e;

let DID_UNIT_NAME_1: UInt8 = 0x41;
let DID_UNIT_NAME_2: UInt8 = 0x42;
let DID_UNIT_NAME_3: UInt8 = 0x43;
let DID_UNIT_NAME_4: UInt8 = 0x44;
let DID_UNIT_NAME_5: UInt8 = 0x45;
let DID_UNIT_NAME_6: UInt8 = 0x46;
let DID_UNIT_NAME_7: UInt8 = 0x47;
let DID_UNIT_NAME_8: UInt8 = 0x48;
let DID_UNIT_NAME_9: UInt8 = 0x49;
let DID_UNIT_NAME_CHAR_COUNT: UInt8 = 0x4a;
let DID_UNIT_NAME_WRITTEN: UInt8 = 0x4b;

let DID_RTC_1: UInt8 = 0x51;
let DID_RTC_2: UInt8 = 0x52;
let DID_PLACEHOLDER_1: UInt8 = 0x53;
let DID_TIMESTAMP_LAST_RUN_1: UInt8 = 0x54;
let DID_TIMESTAMP_LAST_RUN_2: UInt8 = 0x55;
let DID_TIMESTAMP_LAST_RUN_VALID: UInt8 = 0x56;
let DID_TIMESTAMP_LAST_RTC_SYNC_1: UInt8 = 0x57;
let DID_TIMESTAMP_LAST_RTC_SYNC_2: UInt8 = 0x58;
let DID_TIMESTAMP_LAST_RTC_SYNC_VALID: UInt8 = 0x59;
let DID_TIMESTAMP_FILTER_CAL_1: UInt8 = 0x5a;
let DID_TIMESTAMP_FILTER_CAL_2: UInt8 = 0x5b;
let DID_TIMESTAMP_FILTER_CAL_VALID: UInt8 = 0x5c;

let DID_RESULT_BATT_TEMP: UInt8 = 0x61;
let DID_RESULT_BATT_DCIR: UInt8 = 0x62;
let DID_RESULT_POWER_25000: UInt8 = 0x63;
let DID_RESULT_MOTOR_ADC_OFFSET: UInt8  = 0x64;
let DID_RESULT_PRESSURE_ADC_OFFSET: UInt8 = 0x65;


let DID_TEST_1: UInt8 = 0x80;
let DID_TEST_2: UInt8 = 0x81;
let DID_TEST_3: UInt8 = 0x82;
let DID_TEST_4: UInt8 = 0x83;
let DID_CONTROL_KP: UInt8 = 0x84;
let DID_CONTROL_KI: UInt8 = 0x85;
let DID_CONTROL_KD: UInt8 = 0x86;
let DID_CONTROL_KD_SAMPLE_PERIOD: UInt8 = 0x87;
let DID_CONTROL_PRESSURE: UInt8 = 0x88;

let DID_PROMPT_MESSAGE: UInt8 = 0x02;
let DID_PROMPT_MODE_SELECT: UInt8 = 0x01;
let DID_PROMPT_PASSWORD: UInt8 = 0x02;
let DID_PROMPT_SPEED: UInt8 = 0x03;
let DID_PROMPT_KEYPAD_TEST: UInt8 = 0x04;
let DID_PROMPT_BATT_TEMP_TEST: UInt8 = 0x05;
let DID_PROMPT_PRESSURE_CAL_INPUT: UInt8 = 0x06;
let DID_PROMPT_IS_UNIT_EX: UInt8 = 0x07;
let DID_PROMPT_ENSURE_AC_CONNECTED: UInt8 = 0x08;

let DID_NOTICE_MESSAGE: UInt8 = 0x03;
let DID_NOTICE_ACK: UInt8 = 0x01;
let DID_NOTICE_NACK: UInt8 = 0x02;
let DID_NOTICE_UNIT_REPORT: UInt8 = 0x03;
let DID_NOTICE_UNIT_INFO: UInt8 = 0x04;
let DID_NOTICE_UNIT_STATS: UInt8 = 0x05;
let DID_NOTICE_ADC_READ_COMPLETE: UInt8 = 0x06;
let DID_NOTICE_FLASH_READ_COMPLETE: UInt8 = 0x07;
let DID_NOTICE_FACTORY_CAL_COMPLETE: UInt8 = 0x08;
let DID_NOTICE_FACTORY_CAL_FAIL: UInt8 = 0x09;
let DID_NOTICE_USER_CAL_COMPLETE: UInt8 = 0x0a;
let DID_NOTICE_USER_CAL_FAIL: UInt8 = 0x0b;
let DID_NOTICE_PRESSURE_ZERO_CAL_COMPLETE: UInt8 = 0x0c;
let DID_NOTICE_PRESSURE_ZERO_CAL_FAIL: UInt8 = 0x0d;
let DID_NOTICE_PRESSURE_CAL_COMPLETE: UInt8 = 0x0e;
let DID_NOTICE_PRESSURE_CAL_FAIL: UInt8 = 0x0f;
let DID_NOTICE_KEYPAD_TEST_COMPLETE: UInt8 = 0x10;
let DID_NOTICE_KEYPAD_TEST_FAIL: UInt8 = 0x11;
let DID_NOTICE_BATT_TEMP_TEST_COMPLETE: UInt8 = 0x12;
let DID_NOTICE_BATT_TEMP_TEST_FAIL: UInt8 = 0x13;
let DID_NOTICE_CHARGER_TEST_COMPLETE: UInt8 = 0x14;
let DID_NOTICE_CHARGER_TEST_FAIL: UInt8 = 0x15;
let DID_NOTICE_FILTER_SETTINGS: UInt8 = 0x16;
let DID_NOTICE_FILTER_CAL_COMPLETE: UInt8 = 0x17;
let DID_NOTICE_FILTER_CAL_FAIL: UInt8 = 0x18;
let NOTICE_MOTOR_POWER_TEST_START: UInt8 = 0x19;
let NOTICE_MOTOR_POWER_TEST_COMPLETE: UInt8 = 0x1a;
let NOTICE_MOTOR_POWER_TEST_FAIL: UInt8 = 0x1b;
let NOTICE_UNIT_NAME_READ_START: UInt8 = 0x1c;
let NOTICE_UNIT_NAME_READ_FAIL: UInt8 = 0x1d;
let NOTICE_UNIT_NAME_READ_COMPLETE: UInt8 = 0x1e;
let NOTICE_UNIT_NAME_WRITE_START: UInt8 = 0x1f;
let NOTICE_UNIT_NAME_WRITE_FAIL: UInt8 = 0x20;
let NOTICE_UNIT_NAME_WRITE_COMPLETE: UInt8 = 0x21;
let NOTICE_RTC_READ_START: UInt8 = 0x22;
let NOTICE_RTC_READ_FAIL: UInt8 = 0x23;
let NOTICE_RTC_READ_COMPLETE:UInt8 = 0x24;
let NOTICE_RTC_WRITE_START: UInt8 = 0x25;
let NOTICE_RTC_WRITE_FAIL: UInt8 = 0x26;
let NOTICE_RTC_WRITE_COMPLETE: UInt8 = 0x27;
let NOTICE_UNIT_STATS_START: UInt8 = 0x28;
let NOTICE_RUNNING_WHILE_CHARGING_DISABLED: UInt8 = 0x30;



let DID_EVENT_1: UInt8 = 0x04;
let DID_START_CPAP: UInt8 = 0x01;
let DID_CPAP_INIT: UInt8 = 0x02;
let DID_EPAP_RAMP_UP: UInt8 = 0x03;
let DID_NORMAL_CPAP: UInt8 = 0x04;
let DID_BOOST_CPAP0: UInt8 = 0x05;

let EVENT_REQEST_DISCONNECT: UInt8 = 0x06;
let EVENT_UNIT_POWER_UP : UInt8 = 0x07;
let EVENT_UNIT_SLEEP: UInt8 = 0x08;
let EVENT_UNIT_RESUME: UInt8 = 0x09;
let EVENT_MOTOR_START: UInt8 = 0x0a;
let EVENT_MOTOR_STOP: UInt8 = 0x0b;
let EVENT_KEY_ONOFF: UInt8 = 0x0c;
let EVENT_KEY_TEST: UInt8 = 0x0d;
let EVENT_KEY_P_CAL: UInt8 = 0x0e;
let EVENT_KEY_LONG_ONOFF: UInt8 = 0x0f;
let EVENT_KEY_LONG_TEST: UInt8 = 0x10;



let DID_FAULT_EVENT: UInt8 = 0x05;
let DID_LOCKED_ROTOR: UInt8 = 0x01;
let DID_SPEED_OUTSIDE_RANGE: UInt8 = 0x02;
let DID_UNDER_VOLTAGE: UInt8 = 0x03;
let DID_FAULT_BATTERY_DISCONNECTED: UInt8 = 0x04;
let DID_FAULT_BATTERY_TEMP_ABSENT: UInt8 = 0x05;
let DID_FAULT_BATTERY_CHARGE_TIMEOUT: UInt8 = 0x06;




let DID_UNIT_COMMAND: UInt8 = 0x06;
let CMD_SEQ_ID: UInt8 = 0x01;
let CMD_MOTOR_START: UInt8 = 0x02;
let CMD_MOTOR_STOP: UInt8 = 0x03;
let CMD_UNIT_MODE: UInt8 = 0x04;
let CMD_SET_UNIT_SPEED: UInt8 = 0x05;//use in s-mode. Param: [MSB,LSB] for speed in RPM
let CMD_SET_UNIT_PRESSURE: UInt8 = 0x06;
let CMD_SET_UNIT_POWER: UInt8 = 0x07;
let CMD_SET_NORMAL_POWER_STATE: UInt8 = 0x08;// this would reset the unit 3 mins auto-timeout
let CMD_REQUEST_INFO: UInt8 = 0x09;
let CMD_FACTORY_CAL: UInt8 = 0x0a;
let CMD_USER_CAL: UInt8 = 0x0b;
let CMD_MOTOR_POWER_TEST: UInt8 = 0x0c;
let CMD_COMMIT_FLASH: UInt8 = 0x0d;
let CMD_FILTER_SETTINGS_CONFIG: UInt8 = 0x0e;
let CMD_FILTER_CAL: UInt8 = 0x0f;
let CMD_TEST_PROGRAM: UInt8 = 0x10;
let CMD_BUZZER: UInt8 = 0x11;
let CMD_CLIENT_DEV: UInt8 = 0x12;
let CMD_UNIT_NAME = 0x13;
let CMD_UNIT_SERIAL = 0x14;
let CMD_RTC = 0x15;
let CMD_CHARGING_WHILE_RUNNING_ALLOWED = 0x16;
let CMD_CLEAR_FAULT_CODE = 0x17;



//---- level 3 params for CMD_FILTER_SETTINGS_CONFIG
let FILTER_SETTINGS_START: UInt8 = 0x01;
let FILTER_SETTINGS_END: UInt8 = 0x02;

//Params for CMD_REQUEST_INFO
let REQ_BANK_1: UInt8 = 0x01;
let REQ_UNIT_REPORT: UInt8 = 0x01;
let REQ_STATS: UInt8 = 0x02;
let REQ_UNIT_INFO: UInt8 = 0x03;
let REQ_STD_4_PARAMS: UInt8 = 0x04;
let REQ_ADC_READOUT: UInt8 = 0x05;
let REQ_FLASH_READ_OUT: UInt8 = 0x06;
let REQ_FILTER_SETTINGS: UInt8 = 0x07;

//---- level 3 params for CMD_TEST_PROGRAM
let TEST_KEYPAD: UInt8 = 0x01;
let TEST_MOTOR_POWER: UInt8 = 0x02;
let TEST_CHARGER: UInt8 = 0x03;
let TEST_BATTERY_TEMP: UInt8 = 0x04;
let TEST_ZERO_PRESSURE: UInt8 = 0x05;
let TEST_PRESSURE: UInt8 = 0x06;
let TEST_MAX_FLOW_5: UInt8 = 0x07;

//---- level 3 params for CMD_BUZZER;
let BUZ_SHORT_BEEP: UInt8 = 0x01;
let BUZ_LONG_BEEP: UInt8 = 0x02;

//---- level 3 params for CMD_CLIENT_DEV;
let CLIENT_CONNECTION: UInt8 = 0x01;
//client should notify unit once it connected/disconnecting
let CLIENT_CONNECTION_CONNECTED: UInt8 = 0x01; //level 4
let CLIENT_CONNECTION_DISCONNECTING: UInt8 = 0x02; //level 4

//---- level 3 params for CMD_UNIT_NAME
let UNIT_NAME_READ = 0x01;
let UNIT_NAME_WRITE_START = 0x02;
let UNIT_NAME_WRITE_END = 0x03;
let UNIT_NAME_WRITE_ABORT = 0x04;

//---- level 3 params for CMD_RTC
let RTC_READ = 0x01;
let RTC_WRITE_START = 0x02;
let RTC_WRITE_END = 0x03;
let RTC_WRITE_ABORT = 0x04;


let ACK_WITH_ID: UInt8 = 0x08;
let NACK_WITH_ID: UInt8 = 0x09;
//nack reasons
let NO_ERROR: UInt8 = 0x00;
let BAD_CHECKSUM: UInt8 = 0x01;
let COMMAND_NOT_FOUND: UInt8 = 0x02;
let INVALID_PAYLOAD: UInt8 = 0x03;
let INVALID_CONDITION: UInt8 = 0x04;

/**
 * 4 bytes for payload header, DATA_ID( = (byte)0x07),BANK_ID,DATA_ARRAY_ID,LEN (n), DATA (n*2 bytes)
 * LEN(n) MAX : 50
 */
let DID_DATA_ARRAY: UInt8 = 0x07; //Level 1
let DID_BATT_VOLT: UInt8 = 0x01;
let DID_VOLUME: UInt8 = 0x02;
let DID_MOTOR_RUNTIME: UInt8 = 0x03;
let DA_FLASH_BANK_1: UInt8 = 0x04;
let DA_CYCLE_AVERAGE_POWER: UInt8 = 0x05;
let DA_NEGATIVE_PRESSURE_SCORE: UInt8 = 0x06;
let DA_SESSION_NUMBER: UInt8 = 0x07;
let DA_BREATH_NUMBER: UInt8 = 0x08;
let DA_MIN_RPM: UInt8 = 0x09;
let DA_MAX_RPM: UInt8 = 0x0a;
let DA_MIN_PRESSURE: UInt8 = 0x0b;
let DA_MAX_PRESSURE: UInt8 = 0x0c;
let DA_FILTER_STATE: UInt8 = 0x0d;
let DA_ADC_VAL: UInt8 = 0x0e;
let DA_FILTER_COEFF: UInt8 = 0x0f;
let DA_NAME: UInt8 = 0x10;
let DA_NEG_PRESS_SCORE_AUX1: UInt8 = 0x11;
let DA_NEG_PRESS_SCORE_AUX2: UInt8 = 0x12;
let DA_TIMESTAMP_1: UInt8 = 0x13;
let DA_TIMESTAMP_2: UInt8 = 0x14;

let HEADER_LENGTH = 4
let DATA_ARRAY_PAYLOAD_HEADER_LEN = 4
let UNIT_NAME_CHAR_LEN_MAX = 20



